/**
 * Equipment and Category Seed Data
 * Populates database with 7 categories and 30+ equipment items
 */

const categoryData = [
  {
    name: 'Decoration',
    icon: '🎨',
    description: 'Decorative items for beautifying event spaces',
  },
  {
    name: 'Lighting',
    icon: '💡',
    description: 'Professional lighting equipment for events',
  },
  {
    name: 'Catering Equipment',
    icon: '🍽️',
    description: 'Equipment for food service and catering',
  },
  {
    name: 'Furniture',
    icon: '🪑',
    description: 'Tables, chairs, and furniture pieces',
  },
  {
    name: 'Sound & Audio',
    icon: '🔊',
    description: 'Sound systems, speakers, and audio equipment',
  },
  {
    name: 'Media & Production',
    icon: '🎥',
    description: 'Cameras, projectors, screens, and recording equipment',
  },
  {
    name: 'General Supplies',
    icon: '📦',
    description: 'General supplies and accessories',
  },
];

const equipmentData = [
  // DECORATION (9 items)
  {
    name: 'Stage Backdrop - Premium',
    category: 'Decoration',
    description: 'Professional stage backdrop with stand and hardware',
    images: [],
    totalQuantity: 5,
    availableQuantity: 5,
    pricePerDay: 3000,
    condition: 'good',
  },
  {
    name: 'Flower Arrangements - Artificial Set',
    category: 'Decoration',
    description: 'Set of 12 artificial flower arrangements with vases',
    images: [],
    totalQuantity: 8,
    availableQuantity: 8,
    pricePerDay: 1500,
    condition: 'good',
  },
  {
    name: 'Flower Arrangements - Real Bouquets',
    category: 'Decoration',
    description: 'Fresh real flower bouquets (custom arrangements available)',
    images: [],
    totalQuantity: 15,
    availableQuantity: 15,
    pricePerDay: 2500,
    condition: 'good',
  },
  {
    name: 'Drapes & Fabrics - Premium Silk',
    category: 'Decoration',
    description: '100 yards of premium silk drapes in various colors',
    images: [],
    totalQuantity: 10,
    availableQuantity: 10,
    pricePerDay: 2000,
    condition: 'good',
  },
  {
    name: 'Balloon Kits - Birthday Party',
    category: 'Decoration',
    description: 'Complete balloon kit for 50-person birthday party',
    images: [],
    totalQuantity: 12,
    availableQuantity: 12,
    pricePerDay: 500,
    condition: 'good',
  },
  {
    name: 'Wedding Mandap Setup - Traditional',
    category: 'Decoration',
    description: 'Complete traditional wedding mandap with decorations',
    images: [],
    totalQuantity: 3,
    availableQuantity: 3,
    pricePerDay: 8000,
    condition: 'good',
  },
  {
    name: 'Centerpieces - Table Decorations',
    category: 'Decoration',
    description: 'Set of 20 elegant table centerpieces',
    images: [],
    totalQuantity: 6,
    availableQuantity: 6,
    pricePerDay: 1800,
    condition: 'good',
  },
  {
    name: 'LED Decorative Panels - RGB',
    category: 'Decoration',
    description: '10 LED RGB panels for wall/backdrop decoration',
    images: [],
    totalQuantity: 4,
    availableQuantity: 4,
    pricePerDay: 3500,
    condition: 'good',
  },
  {
    name: 'Entrance Arches - Metal Frame',
    category: 'Decoration',
    description: '3 decorative metal arches for entrance decoration',
    images: [],
    totalQuantity: 5,
    availableQuantity: 5,
    pricePerDay: 2200,
    condition: 'good',
  },

  // LIGHTING (7 items)
  {
    name: 'LED Light Kit - Professional',
    category: 'Lighting',
    description: '12 LED lights with stands and color gels',
    images: [],
    totalQuantity: 8,
    availableQuantity: 8,
    pricePerDay: 2500,
    condition: 'good',
  },
  {
    name: 'Spotlights - 500W',
    category: 'Lighting',
    description: 'Set of 4 professional 500W spotlights',
    images: [],
    totalQuantity: 6,
    availableQuantity: 6,
    pricePerDay: 2000,
    condition: 'good',
  },
  {
    name: 'Moving Head Lights - DMX',
    category: 'Lighting',
    description: '6 professional moving head lights with DMX controller',
    images: [],
    totalQuantity: 3,
    availableQuantity: 3,
    pricePerDay: 4000,
    condition: 'good',
  },
  {
    name: 'Fairy Lights - String',
    category: 'Lighting',
    description: '200m of decorative fairy lights',
    images: [],
    totalQuantity: 10,
    availableQuantity: 10,
    pricePerDay: 800,
    condition: 'good',
  },
  {
    name: 'Chandeliers - Crystal',
    category: 'Lighting',
    description: '5 decorative crystal chandeliers',
    images: [],
    totalQuantity: 5,
    availableQuantity: 5,
    pricePerDay: 2200,
    condition: 'good',
  },
  {
    name: 'Outdoor Flood Lights - 1000W',
    category: 'Lighting',
    description: '8 professional outdoor flood lights with stands',
    images: [],
    totalQuantity: 8,
    availableQuantity: 8,
    pricePerDay: 1500,
    condition: 'good',
  },
  {
    name: 'Lighting Controller - Console',
    category: 'Lighting',
    description: 'Professional DMX lighting console for 512 channels',
    images: [],
    totalQuantity: 2,
    availableQuantity: 2,
    pricePerDay: 3000,
    condition: 'good',
  },

  // CATERING EQUIPMENT (6 items)
  {
    name: 'Plates, Spoons & Glasses Set',
    category: 'Catering Equipment',
    description: 'Complete dinnerware set for 200 people',
    images: [],
    totalQuantity: 4,
    availableQuantity: 4,
    pricePerDay: 1200,
    condition: 'good',
  },
  {
    name: 'Buffet Tables - Stainless Steel',
    category: 'Catering Equipment',
    description: '6 professional stainless steel buffet tables',
    images: [],
    totalQuantity: 8,
    availableQuantity: 8,
    pricePerDay: 2000,
    condition: 'good',
  },
  {
    name: 'Food Warmers - Commercial',
    category: 'Catering Equipment',
    description: '4 commercial-grade food warmers with temperature control',
    images: [],
    totalQuantity: 4,
    availableQuantity: 4,
    pricePerDay: 1500,
    condition: 'good',
  },
  {
    name: 'Serving Trays - Assorted',
    category: 'Catering Equipment',
    description: '30 assorted serving trays (various sizes)',
    images: [],
    totalQuantity: 6,
    availableQuantity: 6,
    pricePerDay: 600,
    condition: 'good',
  },
  {
    name: 'Water Dispensers - Large',
    category: 'Catering Equipment',
    description: '3 large water dispensers (5-gallon capacity each)',
    images: [],
    totalQuantity: 3,
    availableQuantity: 3,
    pricePerDay: 800,
    condition: 'good',
  },
  {
    name: 'BBQ Grills - Professional',
    category: 'Catering Equipment',
    description: '2 professional commercial BBQ grills',
    images: [],
    totalQuantity: 2,
    availableQuantity: 2,
    pricePerDay: 3500,
    condition: 'good',
  },

  // FURNITURE (8 items)
  {
    name: 'Chairs - Plastic (White)',
    category: 'Furniture',
    description: 'Set of 50 sturdy plastic chairs',
    images: [],
    totalQuantity: 20,
    availableQuantity: 20,
    pricePerDay: 400,
    condition: 'good',
  },
  {
    name: 'Chairs - VIP/Premium',
    category: 'Furniture',
    description: 'Set of 20 premium padded VIP chairs',
    images: [],
    totalQuantity: 10,
    availableQuantity: 10,
    pricePerDay: 800,
    condition: 'good',
  },
  {
    name: 'Sofas & Couches',
    category: 'Furniture',
    description: '8 premium sofas for lounge areas',
    images: [],
    totalQuantity: 8,
    availableQuantity: 8,
    pricePerDay: 1500,
    condition: 'good',
  },
  {
    name: 'Tables - Round (6-seater)',
    category: 'Furniture',
    description: '25 round tables for 6 people each',
    images: [],
    totalQuantity: 25,
    availableQuantity: 25,
    pricePerDay: 600,
    condition: 'good',
  },
  {
    name: 'Tables - Rectangular (8-seater)',
    category: 'Furniture',
    description: '15 rectangular tables for 8 people each',
    images: [],
    totalQuantity: 15,
    availableQuantity: 15,
    pricePerDay: 700,
    condition: 'good',
  },
  {
    name: 'Stages - Modular Platform',
    category: 'Furniture',
    description: 'Professional modular stage platform (8x8 feet)',
    images: [],
    totalQuantity: 4,
    availableQuantity: 4,
    pricePerDay: 2500,
    condition: 'good',
  },
  {
    name: 'Dance Floors - LED',
    category: 'Furniture',
    description: '2 professional LED dance floors (12x12 feet each)',
    images: [],
    totalQuantity: 2,
    availableQuantity: 2,
    pricePerDay: 5000,
    condition: 'good',
  },
  {
    name: 'Tents & Marquees - Large',
    category: 'Furniture',
    description: '2 large marquees (40x60 feet with full setup)',
    images: [],
    totalQuantity: 2,
    availableQuantity: 2,
    pricePerDay: 8000,
    condition: 'good',
  },

  // SOUND & AUDIO (5 items)
  {
    name: 'Speakers - Professional PA System',
    category: 'Sound & Audio',
    description: 'Complete PA speaker system for 1000+ people',
    images: [],
    totalQuantity: 3,
    availableQuantity: 3,
    pricePerDay: 4000,
    condition: 'good',
  },
  {
    name: 'Microphones - Wireless Set',
    category: 'Sound & Audio',
    description: '6 professional wireless microphones with headsets',
    images: [],
    totalQuantity: 5,
    availableQuantity: 5,
    pricePerDay: 1200,
    condition: 'good',
  },
  {
    name: 'DJ System - Complete',
    category: 'Sound & Audio',
    description: 'Complete DJ system with turntables, mixer, and effects',
    images: [],
    totalQuantity: 4,
    availableQuantity: 4,
    pricePerDay: 3500,
    condition: 'good',
  },
  {
    name: 'Audio Mixers - Professional',
    category: 'Sound & Audio',
    description: '3 professional audio mixing consoles',
    images: [],
    totalQuantity: 3,
    availableQuantity: 3,
    pricePerDay: 2000,
    condition: 'good',
  },
  {
    name: 'Amplifiers - Power',
    category: 'Sound & Audio',
    description: '4 professional power amplifiers (high wattage)',
    images: [],
    totalQuantity: 4,
    availableQuantity: 4,
    pricePerDay: 1500,
    condition: 'good',
  },

  // MEDIA & PRODUCTION (5 items)
  {
    name: 'Cameras - Professional Video',
    category: 'Media & Production',
    description: '2 professional video cameras with accessories',
    images: [],
    totalQuantity: 2,
    availableQuantity: 2,
    pricePerDay: 4000,
    condition: 'good',
  },
  {
    name: 'Tripods - Heavy Duty',
    category: 'Media & Production',
    description: '6 professional heavy-duty camera tripods',
    images: [],
    totalQuantity: 6,
    availableQuantity: 6,
    pricePerDay: 500,
    condition: 'good',
  },
  {
    name: 'LED Screens - Large Format',
    category: 'Media & Production',
    description: '2 large LED screens (10x6 feet each) with controller',
    images: [],
    totalQuantity: 2,
    availableQuantity: 2,
    pricePerDay: 6000,
    condition: 'good',
  },
  {
    name: 'Projectors - 4K',
    category: 'Media & Production',
    description: '3 professional 4K projectors with lenses',
    images: [],
    totalQuantity: 3,
    availableQuantity: 3,
    pricePerDay: 3000,
    condition: 'good',
  },
  {
    name: 'Drone Cameras',
    category: 'Media & Production',
    description: '2 professional drone cameras with 4K capability',
    images: [],
    totalQuantity: 2,
    availableQuantity: 2,
    pricePerDay: 5000,
    condition: 'good',
  },

  // GENERAL SUPPLIES (4 items)
  {
    name: 'Extension Cables - Heavy Duty',
    category: 'General Supplies',
    description: '200m of heavy-duty extension cable (various gauges)',
    images: [],
    totalQuantity: 10,
    availableQuantity: 10,
    pricePerDay: 300,
    condition: 'good',
  },
  {
    name: 'Tape, Glue & Adhesives',
    category: 'General Supplies',
    description: 'Complete kit: gaffer tape, duct tape, glue, fasteners',
    images: [],
    totalQuantity: 8,
    availableQuantity: 8,
    pricePerDay: 200,
    condition: 'good',
  },
  {
    name: 'Batteries & Power Banks',
    category: 'General Supplies',
    description: 'Assorted batteries (AA, AAA, 9V) and power banks',
    images: [],
    totalQuantity: 12,
    availableQuantity: 12,
    pricePerDay: 150,
    condition: 'good',
  },
  {
    name: 'Cleaning Supplies Kit',
    category: 'General Supplies',
    description: 'Complete cleaning supplies for event spaces',
    images: [],
    totalQuantity: 6,
    availableQuantity: 6,
    pricePerDay: 250,
    condition: 'good',
  },
];

module.exports = {
  categoryData,
  equipmentData,
};
