/**
 * Sample event packages built from seeded equipment inventory.
 * Admin can edit pricing; these are created on first package init.
 */

const packageTemplates = [
  {
    name: 'Royal Wedding Package',
    description: 'Complete wedding experience with mandap, premium décor, full catering setup, PA system, and VIP seating.',
    icon: '💒',
    eventTypes: ['wedding'],
    tier: 'vip',
    menuPlan: 'premium',
    services: { decoration: true, lighting: true, cateringSupport: true },
    equipmentNames: [
      { name: 'Wedding Mandap Setup - Traditional', quantity: 1 },
      { name: 'Stage Backdrop - Premium', quantity: 1 },
      { name: 'Chandeliers - Crystal', quantity: 3 },
      { name: 'Speakers - Professional PA System', quantity: 1 },
      { name: 'Buffet Tables - Stainless Steel', quantity: 6 },
      { name: 'Chairs - VIP/Premium', quantity: 20 },
      { name: 'Tables - Round (6-seater)', quantity: 15 },
      { name: 'Plates, Spoons & Glasses Set', quantity: 2 },
    ],
    staffRequired: [
      { role: 'manager', count: 1 },
      { role: 'chef', count: 3 },
      { role: 'waiter', count: 6 },
    ],
    otherCosts: 15000,
    basePrice: 85000,
    pricePerSeat: 2200,
    minSeats: 50,
    maxSeats: 250,
    highlights: [
      'Traditional mandap with premium silk drapes',
      'Premium menu with live catering support',
      'Crystal chandeliers & stage backdrop',
      'Full PA system for 1000+ guests',
    ],
  },
  {
    name: 'Corporate Excellence Package',
    description: 'Professional corporate event with LED screens, lighting, modular stage, and classic buffet service.',
    icon: '🏢',
    eventTypes: ['corporate'],
    tier: 'premium',
    menuPlan: 'classic',
    services: { decoration: true, lighting: true, cateringSupport: true },
    equipmentNames: [
      { name: 'LED Screens - Large Format', quantity: 1 },
      { name: 'Stages - Modular Platform', quantity: 2 },
      { name: 'LED Light Kit - Professional', quantity: 1 },
      { name: 'Microphones - Wireless Set', quantity: 1 },
      { name: 'Projectors - 4K', quantity: 2 },
      { name: 'Tables - Rectangular (8-seater)', quantity: 10 },
      { name: 'Chairs - Plastic (White)', quantity: 10 },
      { name: 'Buffet Tables - Stainless Steel', quantity: 4 },
    ],
    staffRequired: [
      { role: 'team_lead', count: 1 },
      { role: 'chef', count: 2 },
      { role: 'waiter', count: 4 },
    ],
    otherCosts: 8000,
    basePrice: 45000,
    pricePerSeat: 1400,
    minSeats: 30,
    maxSeats: 120,
    highlights: [
      '4K projectors & large LED screen',
      'Modular stage with professional lighting',
      'Wireless microphone set',
      'Classic buffet with full catering crew',
    ],
  },
  {
    name: 'Birthday Celebration Package',
    description: 'Fun birthday setup with balloon décor, fairy lights, DJ system, dance floor, and party catering.',
    icon: '🎂',
    eventTypes: ['birthday'],
    tier: 'standard',
    menuPlan: 'basic',
    services: { decoration: true, lighting: true, cateringSupport: true },
    equipmentNames: [
      { name: 'Balloon Kits - Birthday Party', quantity: 2 },
      { name: 'Fairy Lights - String', quantity: 1 },
      { name: 'DJ System - Complete', quantity: 1 },
      { name: 'Dance Floors - LED', quantity: 1 },
      { name: 'Tables - Round (6-seater)', quantity: 8 },
      { name: 'Chairs - Plastic (White)', quantity: 8 },
      { name: 'Food Warmers - Commercial', quantity: 2 },
      { name: 'Serving Trays - Assorted', quantity: 2 },
    ],
    staffRequired: [
      { role: 'chef', count: 1 },
      { role: 'waiter', count: 3 },
    ],
    otherCosts: 5000,
    basePrice: 22000,
    pricePerSeat: 850,
    minSeats: 20,
    maxSeats: 80,
    highlights: [
      'Balloon kits & fairy light décor',
      'Complete DJ system with LED dance floor',
      'Basic party menu with catering support',
      'Ideal for 20–80 guests',
    ],
  },
  {
    name: 'Private Social Package',
    description: 'Elegant private gathering with lounge furniture, ambient lighting, sound system, and classic dining.',
    icon: '🥂',
    eventTypes: ['private'],
    tier: 'premium',
    menuPlan: 'classic',
    services: { decoration: true, lighting: false, cateringSupport: true },
    equipmentNames: [
      { name: 'Sofas & Couches', quantity: 4 },
      { name: 'Centerpieces - Table Decorations', quantity: 1 },
      { name: 'Spotlights - 500W', quantity: 1 },
      { name: 'Speakers - Professional PA System', quantity: 1 },
      { name: 'Tables - Round (6-seater)', quantity: 10 },
      { name: 'Chairs - VIP/Premium', quantity: 10 },
      { name: 'Water Dispensers - Large', quantity: 2 },
      { name: 'Plates, Spoons & Glasses Set', quantity: 1 },
    ],
    staffRequired: [
      { role: 'chef', count: 2 },
      { role: 'waiter', count: 4 },
    ],
    otherCosts: 6000,
    basePrice: 35000,
    pricePerSeat: 1200,
    minSeats: 25,
    maxSeats: 100,
    highlights: [
      'Premium lounge seating & table centerpieces',
      'Classic menu with dedicated wait staff',
      'PA system for speeches & background music',
      'Perfect for anniversaries & social events',
    ],
  },
];

module.exports = { packageTemplates };
